version: '3'
networks:
      randint-overlay:
        external: true
services:
    web:
        image: 192.168.1.150:5111/teamrandint/webserver:latest
        depends_on:
            - "transaction"
            - "database"
            - "audit"
        environment:
            - SERVICE_PORTS=${webport}
        env_file:
            - .env
        ports:
            - "${webport}:${webport}"
        networks:
          - randint-overlay
        deploy:
          replicas: ${num_web}
          placement:
            constraints: 
                - node.hostname == b143.seng
    audit:
        image: 192.168.1.150:5111/teamrandint/auditserver:latest
        env_file:
            - .env
        ports:
            - "${auditport}:${auditport}"
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.hostname == b141.seng
    database:
        image: 192.168.1.150:5111/teamrandint/database:latest
        env_file:
            - .env
        ports:
            - ${dbport}:${dbport}
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.hostname == b153.seng
    transaction:
        image: 192.168.1.150:5111/teamrandint/transactionserver:latest
        depends_on:
            - "database"
            - "audit"
            - "quote"
        env_file:
            - .env
        ports:
            - ${transport}:${transport}
        networks:
          - randint-overlay
        deploy:
            replicas: ${num_trans}
            placement:
                constraints: 
                    - node.hostname == b153.seng
    quote:
        image: 192.168.1.150:5111/teamrandint/quoteserver:latest
        depends_on:
            - "audit"
        env_file:
            - .env
        ports:
            - ${quoteport}:${quoteport}
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.hostname == b143.seng
    trigger:
        image: 192.168.1.150:5111/teamrandint/triggerserver:latest
        depends_on:
            - "audit"
        env_file:
            - .env
        ports:
            - ${triggerport}:${triggerport}
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.hostname == b149.seng
    proxy_web:
        image: 192.168.1.150:5111/teamrandint/haproxy:latest
        depends_on:
          - web
        environment:
          - BALANCE=url_param username
          - OPTION=http-keep-alive,prefer-last-server,redispatch,dontlognull
          - MAXCONN=9999
          - EXTRA_ROUTE_SETTINGS=maxconn 999
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - ${proxyport}:${proxyport}
          - "1936:1936"
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.role == manager
                - node.hostname == b138.seng
                - node.hostname != b130.seng
                - node.hostname != b131.seng
                - node.hostname != b132.seng
                - node.hostname != b136.seng
                - node.hostname != b153.seng
                - node.hostname != b147.seng
