version: '3'
networks:
      randint-overlay:
        external: true
services:
    web:
        image: teamrandint/webserver
        deploy:
            replicas: ${num_web}
        depends_on:
            - "transaction"
            - "database"
            - "audit"
        environment:
            - SERVICE_PORTS=${webport}
        env_file:
            - .env
        ports:
            - "${webport}:${webport}"
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.hostname != b131.seng
                - node.hostname != b132.seng
                - node.hostname != b136.seng
    audit:
        image: teamrandint/auditserver
        env_file:
            - .env
        ports:
            - "${auditport}:${auditport}"
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.hostname != b131.seng
                - node.hostname != b132.seng
                - node.hostname != b136.seng
    database:
        image: teamrandint/database
        env_file:
            - .env
        ports:
            - ${dbport}:${dbport}
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.hostname != b131.seng
                - node.hostname != b132.seng
                - node.hostname != b136.seng
    transaction:
        image: teamrandint/transactionserver
        depends_on:
            - "database"
            - "audit"
            - "quote"
        env_file:
            - .env
        ports:
            - ${transport}:${transport}
        networks:
          - randint-overlay
        deploy:
            replicas: ${num_trans}
            placement:
                constraints: 
                    - node.hostname != b131.seng
                    - node.hostname != b132.seng
                    - node.hostname != b136.seng
    quote:
        image: teamrandint/quoteserver
        depends_on:
            - "audit"
        env_file:
            - .env
        ports:
            - ${quoteport}:${quoteport}
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.hostname != b131.seng
                - node.hostname != b132.seng
                - node.hostname != b136.seng
    trigger:
        image: teamrandint/triggerserver
        depends_on:
            - "audit"
        env_file:
            - .env
        ports:
            - ${triggerport}:${triggerport}
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.hostname != b131.seng
                - node.hostname != b132.seng
                - node.hostname != b136.seng
    proxy_web:
        image: dockercloud/haproxy
        depends_on:
          - web
        environment:
          - BALANCE=url_param username
          - OPTION=http-keep-alive,prefer-last-server,redispatch,dontlognull
          - MAXCONN=9999
          - EXTRA_ROUTE_SETTINGS=maxconn 999
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - ${proxyport}:${proxyport}
          - "1936:1936"
        networks:
          - randint-overlay
        deploy:
          placement:
            constraints: 
                - node.role == manager
                - node.hostname != b131.seng
                - node.hostname != b132.seng
                - node.hostname != b136.seng
