version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 172.20.0.0/16

services:
    web:
        build:
            context: ../WebServer
            dockerfile: Dockerfile
            args:
                - webaddr
                - webport
                - auditaddr
                - auditport
                - transaddr
                - transport
        depends_on:
            - "transaction"
            - "database"
            - "audit"
        env_file:
            - .env
        ports:
            - "${webport}:${webport}"
        networks:
            app_net:
                ipv4_address: ${webaddr}
    audit:
        build:
            context: ../auditserver
            dockerfile: Dockerfile
            args:
                - auditaddr
                - auditport
        env_file:
            - .env
        ports:
            - "${auditport}:${auditport}"
        networks:
            app_net:
                ipv4_address: ${auditaddr}
    database:
        build:
            context: ../database
            dockerfile: Dockerfile
            args:
                - dbaddr
                - dbport
        env_file:
            - .env
        ports:
            - "${dbport}:${dbport}"
        networks:
            app_net:
                ipv4_address: ${dbaddr}
    transaction:
        build:
            context: ../transaction-server
            dockerfile: Dockerfile
            args:
                - transaddr
                - transport
                - dbaddr
                - dbport
                - auditaddr
                - auditport
                - quoteclientaddr
                - quoteclientport 
        links:
            - database
        depends_on:
            - "database"
            - "audit"
            - "quote"
        env_file:
            - .env
        ports:
            - "${transport}:${transport}"
        networks:
            app_net:
                ipv4_address: ${transaddr}
    quote:
        build:
            context: ../quoteserver
            dockerfile: Dockerfile
            args:
                - auditaddr
                - auditport
                - quoteaddr
                - quoteport 
        depends_on:
            - "audit"
        env_file:
            - .env
        ports:
            - "${quoteport}:${quoteport}"
        networks:
            app_net:
                ipv4_address: ${quoteaddr}
    trigger:
        build:
            context: ../triggerserver
            dockerfile: Dockerfile
            args:
                - transaddr
                - transport
                - triggeraddr
                - triggerport
        depends_on:
            - "quote"
        env_file:
            - .env
        ports:
            - "${triggerport}:${triggerport}"
        networks:
            app_net:
                ipv4_address: ${triggeraddr}
