version: '3'
services:
    web:
        build:
            context: ../WebServer
            dockerfile: Dockerfile
            args:
                - webaddr
                - webport
                - auditaddr
                - auditport
                - transaddr
                - transport
        depends_on:
            - "transaction"
            - "database"
            - "audit"
        env_file:
            - .env
        ports:
            - "${webport}:${webport}"
    audit:
        build:
            context: ../auditserver
            dockerfile: Dockerfile
            args:
                - auditaddr
                - auditport
        env_file:
            - .env
        ports:
            - "${auditport}:${auditport}"
    database:
        build:
            context: ../database
            dockerfile: Dockerfile
            args:
                - dbaddr
                - dbport
        env_file:
            - .env
        ports:
            - "${dbport}:${dbport}"
    transaction:
        build:
            context: ../transaction-server
            dockerfile: Dockerfile
            args:
                - transaddr
                - transport
                - dbaddr
                - dbport
                - auditaddr
                - auditport
                - quoteclientaddr
                - quoteclientport 
        links:
            - database
        depends_on:
            - "database"
            - "audit"
            - "quote"
        env_file:
            - .env
        ports:
            - "${transport}:${transport}"
    quote:
        build:
            context: ../quoteserver
            dockerfile: Dockerfile
            args:
                - auditaddr
                - auditport
                - quoteaddr
                - quoteport 
        depends_on:
            - "audit"
        env_file:
            - .env
        ports:
            - "${quoteport}:${quoteport}"
